// Generated by scripts/extract-showdown-moves.mjs — do not edit by hand.
//
// Move values PokéAPI gets wrong or never supplies, mirrored from Pokémon Showdown's
// data/moves.ts (MIT). PokéAPI's `move_meta` table stops at generation 7, so most gen-8+
// moves decode with no multi-hit, drain, ailment, flinch or crit-rate at all, and it writes
// `0` rather than null for a move that never misses.
//
// Only plain data lives here. Moves Showdown expresses as callbacks (variable power, volatile
// statuses, weather) need engine support instead — see `VariableDamage` and the script's report.

/// One move's corrections. Every field is optional: an absent field keeps the PokéAPI value.
struct ShowdownMoveOverride: Sendable {
    /// The move never misses — the engine spells that `MoveSpec.accuracy == nil`.
    var alwaysHits = false
    var accuracy: Int?
    var power: Int?
    var critRate: Int?
    var drain: Int?
    var healing: Int?
    var minHits: Int?
    var maxHits: Int?
    var ailment: String?
    var ailmentChance: Int?
    var statChance: Int?
    var flinchChance: Int?
}

/// The categorical effect a move calls, if any. The engine implements each effect once and
/// looks up *which* move calls it here, instead of keeping its own list of ids.
struct ShowdownMoveEffect: Sendable {
    /// Showdown's own keys — the engine maps the ones it models and ignores the rest.
    var weather: String?
    var terrain: String?
    var sideCondition: String?
    /// Which side the condition lands on: `allySide` (Reflect) or `foeSide` (Spikes).
    var sideConditionTarget: String?
    var volatileStatus: String?
}

enum ShowdownMoveData {
    /// Keyed by PokéAPI move id (Showdown's `num`).
    static let overrides: [Int: ShowdownMoveOverride] = [
        290: .init(ailment: "paralysis"),  // Secret Power
        622: .init(power: 1),  // Breakneck Blitz
        624: .init(power: 1),  // All-Out Pummeling
        626: .init(power: 1),  // Supersonic Skystrike
        628: .init(power: 1),  // Acid Downpour
        630: .init(power: 1),  // Tectonic Rage
        632: .init(power: 1),  // Continental Crush
        634: .init(power: 1),  // Savage Spin-Out
        636: .init(power: 1),  // Never-Ending Nightmare
        638: .init(power: 1),  // Corkscrew Crash
        640: .init(power: 1),  // Inferno Overdrive
        642: .init(power: 1),  // Hydro Vortex
        644: .init(power: 1),  // Bloom Doom
        646: .init(power: 1),  // Gigavolt Havoc
        648: .init(power: 1),  // Shattered Psyche
        650: .init(power: 1),  // Subzero Slammer
        652: .init(power: 1),  // Devastating Drake
        654: .init(power: 1),  // Black Hole Eclipse
        656: .init(power: 1),  // Twinkle Tackle
        733: .init(drain: 50),  // Bouncy Bubble
        831: .init(statChance: 30),  // Springtide Storm
        834: .init(drain: -33),  // Wave Crash
        836: .init(flinchChance: 30),  // Mountain Gale
        839: .init(ailment: "poison", ailmentChance: 50),  // Barb Barrage
        840: .init(critRate: 1),  // Esper Wing
        841: .init(statChance: 100),  // Bitter Malice
        843: .init(critRate: 1, statChance: 50),  // Triple Arrows
        844: .init(ailment: "burn", ailmentChance: 30),  // Infernal Parade
        846: .init(statChance: 30),  // Bleakwind Storm
        847: .init(ailment: "paralysis", ailmentChance: 20),  // Wildbolt Storm
        848: .init(ailment: "burn", ailmentChance: 20),  // Sandsear Storm
        853: .init(ailment: "confusion", ailmentChance: 30),  // Axe Kick
        855: .init(statChance: 100),  // Lumina Crash
        860: .init(minHits: 10, maxHits: 10),  // Population Bomb
        865: .init(minHits: 3, maxHits: 3),  // Triple Dive
        866: .init(ailment: "poison", ailmentChance: 100),  // Mortal Spin
        877: .init(power: 0),  // Ruination
        884: .init(statChance: 100),  // Pounce
        886: .init(statChance: 100),  // Chilling Water
        888: .init(minHits: 2, maxHits: 2),  // Twin Beam
        891: .init(drain: 50),  // Bitter Blade
        894: .init(power: 0),  // Comeuppance
        895: .init(critRate: 1),  // Aqua Cutter
        896: .init(ailment: "burn", ailmentChance: 30),  // Blazing Torque
        897: .init(ailment: "sleep", ailmentChance: 10),  // Wicked Torque
        898: .init(ailment: "poison", ailmentChance: 30),  // Noxious Torque
        899: .init(ailment: "paralysis", ailmentChance: 30),  // Combat Torque
        900: .init(ailment: "confusion", ailmentChance: 30),  // Magical Torque
        902: .init(drain: 50, ailment: "burn", ailmentChance: 20),  // Matcha Gotcha
        904: .init(critRate: 1),  // Ivy Cudgel
        908: .init(alwaysHits: true),  // Burning Bulwark
        911: .init(alwaysHits: true, minHits: 2, maxHits: 2),  // Tachyon Cutter
        913: .init(alwaysHits: true),  // Dragon Cheer
        918: .init(flinchChance: 100),  // Upper Hand
        919: .init(ailment: "poison", ailmentChance: 50),  // Malignant Chain
    ]

    /// Keyed the same way. Present only for moves that call one of the categorical effects.
    static let effects: [Int: ShowdownMoveEffect] = [
        20: .init(volatileStatus: "partiallytrapped"),  // Bind
        35: .init(volatileStatus: "partiallytrapped"),  // Wrap
        50: .init(volatileStatus: "disable"),  // Disable
        54: .init(sideCondition: "mist", sideConditionTarget: "allySide"),  // Mist
        73: .init(volatileStatus: "leechseed"),  // Leech Seed
        83: .init(volatileStatus: "partiallytrapped"),  // Fire Spin
        107: .init(volatileStatus: "minimize"),  // Minimize
        111: .init(volatileStatus: "defensecurl"),  // Defense Curl
        113: .init(sideCondition: "lightscreen", sideConditionTarget: "allySide"),  // Light Screen
        115: .init(sideCondition: "reflect", sideConditionTarget: "allySide"),  // Reflect
        116: .init(volatileStatus: "focusenergy"),  // Focus Energy
        117: .init(volatileStatus: "bide"),  // Bide
        128: .init(volatileStatus: "partiallytrapped"),  // Clamp
        164: .init(volatileStatus: "substitute"),  // Substitute
        171: .init(volatileStatus: "nightmare"),  // Nightmare
        174: .init(volatileStatus: "curse"),  // Curse
        182: .init(volatileStatus: "protect"),  // Protect
        191: .init(sideCondition: "spikes", sideConditionTarget: "foeSide"),  // Spikes
        193: .init(volatileStatus: "foresight"),  // Foresight
        194: .init(volatileStatus: "destinybond"),  // Destiny Bond
        197: .init(volatileStatus: "protect"),  // Detect
        201: .init(weather: "Sandstorm"),  // Sandstorm
        203: .init(volatileStatus: "endure"),  // Endure
        213: .init(volatileStatus: "attract"),  // Attract
        219: .init(sideCondition: "safeguard", sideConditionTarget: "allySide"),  // Safeguard
        227: .init(volatileStatus: "encore"),  // Encore
        240: .init(weather: "RainDance"),  // Rain Dance
        241: .init(weather: "sunnyday"),  // Sunny Day
        250: .init(volatileStatus: "partiallytrapped"),  // Whirlpool
        254: .init(volatileStatus: "stockpile"),  // Stockpile
        258: .init(weather: "hail"),  // Hail
        259: .init(volatileStatus: "torment"),  // Torment
        266: .init(volatileStatus: "followme"),  // Follow Me
        268: .init(volatileStatus: "charge"),  // Charge
        269: .init(volatileStatus: "taunt"),  // Taunt
        270: .init(volatileStatus: "helpinghand"),  // Helping Hand
        275: .init(volatileStatus: "ingrain"),  // Ingrain
        277: .init(volatileStatus: "magiccoat"),  // Magic Coat
        281: .init(volatileStatus: "yawn"),  // Yawn
        286: .init(volatileStatus: "imprison"),  // Imprison
        288: .init(volatileStatus: "grudge"),  // Grudge
        289: .init(volatileStatus: "snatch"),  // Snatch
        316: .init(volatileStatus: "foresight"),  // Odor Sleuth
        328: .init(volatileStatus: "partiallytrapped"),  // Sand Tomb
        357: .init(volatileStatus: "miracleeye"),  // Miracle Eye
        366: .init(sideCondition: "tailwind", sideConditionTarget: "allySide"),  // Tailwind
        373: .init(volatileStatus: "embargo"),  // Embargo
        377: .init(volatileStatus: "healblock"),  // Heal Block
        379: .init(volatileStatus: "powertrick"),  // Power Trick
        380: .init(volatileStatus: "gastroacid"),  // Gastro Acid
        381: .init(sideCondition: "luckychant", sideConditionTarget: "allySide"),  // Lucky Chant
        390: .init(sideCondition: "toxicspikes", sideConditionTarget: "foeSide"),  // Toxic Spikes
        392: .init(volatileStatus: "aquaring"),  // Aqua Ring
        393: .init(volatileStatus: "magnetrise"),  // Magnet Rise
        446: .init(sideCondition: "stealthrock", sideConditionTarget: "foeSide"),  // Stealth Rock
        463: .init(volatileStatus: "partiallytrapped"),  // Magma Storm
        469: .init(sideCondition: "wideguard", sideConditionTarget: "allySide"),  // Wide Guard
        476: .init(volatileStatus: "ragepowder"),  // Rage Powder
        477: .init(volatileStatus: "telekinesis"),  // Telekinesis
        479: .init(volatileStatus: "smackdown"),  // Smack Down
        501: .init(sideCondition: "quickguard", sideConditionTarget: "allySide"),  // Quick Guard
        561: .init(sideCondition: "matblock", sideConditionTarget: "allySide"),  // Mat Block
        564: .init(sideCondition: "stickyweb", sideConditionTarget: "foeSide"),  // Sticky Web
        578: .init(sideCondition: "craftyshield", sideConditionTarget: "allySide"),  // Crafty Shield
        580: .init(terrain: "grassyterrain"),  // Grassy Terrain
        581: .init(terrain: "mistyterrain"),  // Misty Terrain
        582: .init(volatileStatus: "electrify"),  // Electrify
        588: .init(volatileStatus: "kingsshield"),  // King's Shield
        596: .init(volatileStatus: "spikyshield"),  // Spiky Shield
        600: .init(volatileStatus: "powder"),  // Powder
        604: .init(terrain: "electricterrain"),  // Electric Terrain
        611: .init(volatileStatus: "partiallytrapped"),  // Infestation
        614: .init(volatileStatus: "smackdown"),  // Thousand Arrows
        661: .init(volatileStatus: "banefulbunker"),  // Baneful Bunker
        664: .init(volatileStatus: "sparklingaria"),  // Sparkling Aria
        671: .init(volatileStatus: "spotlight"),  // Spotlight
        673: .init(volatileStatus: "laserfocus"),  // Laser Focus
        678: .init(terrain: "psychicterrain"),  // Psychic Terrain
        694: .init(sideCondition: "auroraveil", sideConditionTarget: "allySide"),  // Aurora Veil
        743: .init(volatileStatus: "maxguard"),  // Max Guard
        748: .init(volatileStatus: "noretreat"),  // No Retreat
        749: .init(volatileStatus: "tarshot"),  // Tar Shot
        753: .init(volatileStatus: "octolock"),  // Octolock
        779: .init(volatileStatus: "partiallytrapped"),  // Snap Trap
        792: .init(volatileStatus: "obstruct"),  // Obstruct
        819: .init(volatileStatus: "partiallytrapped"),  // Thunder Cage
        829: .init(volatileStatus: "powershift"),  // Power Shift
        852: .init(volatileStatus: "silktrap"),  // Silk Trap
        864: .init(volatileStatus: "saltcure"),  // Salt Cure
        880: .init(volatileStatus: "substitute"),  // Shed Tail
        881: .init(weather: "snowscape"),  // Chilly Reception
        883: .init(weather: "snowscape"),  // Snowscape
        903: .init(volatileStatus: "syrupbomb"),  // Syrup Bomb
        908: .init(volatileStatus: "burningbulwark"),  // Burning Bulwark
        913: .init(volatileStatus: "dragoncheer"),  // Dragon Cheer
        917: .init(volatileStatus: "healblock"),  // Psychic Noise
    ]

    /// Moves a guard (Protect and its kin) does **not** stop: they point at an opponent and
    /// Showdown leaves the `protect` flag off. The exceptions are the list because the rule is
    /// "everything is blocked" — a hand-kept list of blocked moves would go stale in silence.
    static let ignoringGuard: Set<Int> = [
        18,  // Whirlwind
        46,  // Roar
        119,  // Mirror Move
        144,  // Transform
        166,  // Sketch
        174,  // Curse
        176,  // Conversion 2
        212,  // Mean Look
        215,  // Heal Bell
        244,  // Psych Up
        248,  // Future Sight
        267,  // Nature Power
        272,  // Role Play
        312,  // Aromatherapy
        335,  // Block
        353,  // Doom Desire
        364,  // Feint
        467,  // Shadow Force
        495,  // After You
        516,  // Bestow
        566,  // Phantom Force
        589,  // Play Nice
        590,  // Confide
        593,  // Hyperspace Hole
        621,  // Hyperspace Fury
        622,  // Breakneck Blitz
        624,  // All-Out Pummeling
        626,  // Supersonic Skystrike
        628,  // Acid Downpour
        630,  // Tectonic Rage
        632,  // Continental Crush
        634,  // Savage Spin-Out
        636,  // Never-Ending Nightmare
        638,  // Corkscrew Crash
        640,  // Inferno Overdrive
        642,  // Hydro Vortex
        644,  // Bloom Doom
        646,  // Gigavolt Havoc
        648,  // Shattered Psyche
        650,  // Subzero Slammer
        652,  // Devastating Drake
        654,  // Black Hole Eclipse
        656,  // Twinkle Tackle
        658,  // Catastropika
        695,  // Sinister Arrow Raid
        696,  // Malicious Moonsault
        697,  // Oceanic Operetta
        698,  // Guardian of Alola
        699,  // Soul-Stealing 7-Star Strike
        700,  // Stoked Sparksurfer
        701,  // Pulverizing Pancake
        703,  // Genesis Supernova
        715,  // Tearful Look
        719,  // 10,000,000 Volt Thunderbolt
        723,  // Light That Burns the Sky
        724,  // Searing Sunraze Smash
        725,  // Menacing Moonraze Maelstrom
        726,  // Let's Snuggle Forever
        727,  // Splintered Stormshards
        728,  // Clangorous Soulblaze
        757,  // Max Flare
        758,  // Max Flutterby
        759,  // Max Lightning
        760,  // Max Strike
        761,  // Max Knuckle
        762,  // Max Phantasm
        763,  // Max Hailstorm
        764,  // Max Ooze
        765,  // Max Geyser
        766,  // Max Airstream
        767,  // Max Starfall
        768,  // Max Wyrmwind
        769,  // Max Mindstorm
        770,  // Max Rockfall
        771,  // Max Quake
        772,  // Max Darkness
        773,  // Max Overgrowth
        774,  // Max Steelspike
        777,  // Decorate
        867,  // Doodle
        887,  // Hyper Drill
        910,  // Mighty Cleave
    ]

    /// Moves that hit a Minimized target harder — double damage, and the accuracy roll is
    /// skipped. Showdown carries this as the `minimize` move flag; the engine implements the
    /// rule once and asks here which moves carry the flag.
    static let hittingMinimizedHarder: Set<Int> = [
        23,  // Stomp
        34,  // Body Slam
        407,  // Dragon Rush
        484,  // Heavy Slam
        535,  // Heat Crash
        537,  // Steamroller
        560,  // Flying Press
        696,  // Malicious Moonsault
        916,  // Supercell Slam
    ]

    /// Moves whose base power doubles while the user carries Defense Curl's volatile. Showdown
    /// keeps the check inside each move's own base-power callback, so this set is read out of
    /// those callbacks rather than kept by hand.
    static let doubledByDefenseCurl: Set<Int> = [
        205,  // Rollout
        301,  // Ice Ball
    ]

    /// Moves that touch the target — Showdown's `contact` move flag. The engine implements the
    /// contact rule once (Rocky Helmet, Sticky Barb, Protective Pads) and asks here which moves
    /// carry the flag; PokéAPI has no contact column at all, so nothing else can answer.
    static let makingContact: Set<Int> = [
        1,  // Pound
        2,  // Karate Chop
        3,  // Double Slap
        4,  // Comet Punch
        5,  // Mega Punch
        7,  // Fire Punch
        8,  // Ice Punch
        9,  // Thunder Punch
        10,  // Scratch
        11,  // Vise Grip
        12,  // Guillotine
        15,  // Cut
        17,  // Wing Attack
        19,  // Fly
        20,  // Bind
        21,  // Slam
        22,  // Vine Whip
        23,  // Stomp
        24,  // Double Kick
        25,  // Mega Kick
        26,  // Jump Kick
        27,  // Rolling Kick
        29,  // Headbutt
        30,  // Horn Attack
        31,  // Fury Attack
        32,  // Horn Drill
        33,  // Tackle
        34,  // Body Slam
        35,  // Wrap
        36,  // Take Down
        37,  // Thrash
        38,  // Double-Edge
        44,  // Bite
        64,  // Peck
        65,  // Drill Peck
        66,  // Submission
        67,  // Low Kick
        68,  // Counter
        69,  // Seismic Toss
        70,  // Strength
        80,  // Petal Dance
        91,  // Dig
        98,  // Quick Attack
        99,  // Rage
        117,  // Bide
        122,  // Lick
        127,  // Waterfall
        128,  // Clamp
        130,  // Skull Bash
        132,  // Constrict
        136,  // High Jump Kick
        141,  // Leech Life
        146,  // Dizzy Punch
        152,  // Crabhammer
        154,  // Fury Swipes
        158,  // Hyper Fang
        162,  // Super Fang
        163,  // Slash
        165,  // Struggle
        167,  // Triple Kick
        168,  // Thief
        172,  // Flame Wheel
        175,  // Flail
        179,  // Reversal
        183,  // Mach Punch
        185,  // Feint Attack
        200,  // Outrage
        205,  // Rollout
        206,  // False Swipe
        209,  // Spark
        210,  // Fury Cutter
        211,  // Steel Wing
        216,  // Return
        218,  // Frustration
        223,  // Dynamic Punch
        224,  // Megahorn
        228,  // Pursuit
        229,  // Rapid Spin
        231,  // Iron Tail
        232,  // Metal Claw
        233,  // Vital Throw
        238,  // Cross Chop
        242,  // Crunch
        245,  // Extreme Speed
        249,  // Rock Smash
        252,  // Fake Out
        263,  // Facade
        264,  // Focus Punch
        265,  // Smelling Salts
        276,  // Superpower
        279,  // Revenge
        280,  // Brick Break
        282,  // Knock Off
        283,  // Endeavor
        291,  // Dive
        292,  // Arm Thrust
        299,  // Blaze Kick
        301,  // Ice Ball
        302,  // Needle Arm
        305,  // Poison Fang
        306,  // Crush Claw
        309,  // Meteor Mash
        310,  // Astonish
        325,  // Shadow Punch
        327,  // Sky Uppercut
        332,  // Aerial Ace
        337,  // Dragon Claw
        340,  // Bounce
        342,  // Poison Tail
        343,  // Covet
        344,  // Volt Tackle
        348,  // Leaf Blade
        358,  // Wake-Up Slap
        359,  // Hammer Arm
        360,  // Gyro Ball
        365,  // Pluck
        369,  // U-turn
        370,  // Close Combat
        371,  // Payback
        372,  // Assurance
        376,  // Trump Card
        378,  // Wring Out
        386,  // Punishment
        387,  // Last Resort
        389,  // Sucker Punch
        394,  // Flare Blitz
        395,  // Force Palm
        398,  // Poison Jab
        400,  // Night Slash
        401,  // Aqua Tail
        404,  // X-Scissor
        407,  // Dragon Rush
        409,  // Drain Punch
        413,  // Brave Bird
        416,  // Giga Impact
        418,  // Bullet Punch
        419,  // Avalanche
        421,  // Shadow Claw
        422,  // Thunder Fang
        423,  // Ice Fang
        424,  // Fire Fang
        425,  // Shadow Sneak
        428,  // Zen Headbutt
        431,  // Rock Climb
        438,  // Power Whip
        440,  // Cross Poison
        442,  // Iron Head
        447,  // Grass Knot
        450,  // Bug Bite
        452,  // Wood Hammer
        453,  // Aqua Jet
        457,  // Head Smash
        458,  // Double Hit
        462,  // Crush Grip
        467,  // Shadow Force
        480,  // Storm Throw
        484,  // Heavy Slam
        488,  // Flame Charge
        490,  // Low Sweep
        492,  // Foul Play
        498,  // Chip Away
        507,  // Sky Drop
        509,  // Circle Throw
        512,  // Acrobatics
        514,  // Retaliate
        525,  // Dragon Tail
        528,  // Wild Charge
        529,  // Drill Run
        530,  // Dual Chop
        531,  // Heart Stamp
        532,  // Horn Leech
        533,  // Sacred Sword
        534,  // Razor Shell
        535,  // Heat Crash
        537,  // Steamroller
        541,  // Tail Slap
        543,  // Head Charge
        544,  // Gear Grind
        550,  // Bolt Strike
        557,  // V-create
        560,  // Flying Press
        565,  // Fell Stinger
        566,  // Phantom Force
        577,  // Draining Kiss
        583,  // Play Rough
        609,  // Nuzzle
        610,  // Hold Back
        611,  // Infestation
        612,  // Power-Up Punch
        620,  // Dragon Ascent
        658,  // Catastropika
        660,  // First Impression
        663,  // Darkest Lariat
        665,  // Ice Hammer
        667,  // High Horsepower
        669,  // Solar Blade
        675,  // Throat Chop
        677,  // Anchor Shot
        679,  // Lunge
        680,  // Fire Lash
        681,  // Power Trip
        684,  // Smart Strike
        688,  // Trop Kick
        692,  // Dragon Hammer
        693,  // Brutal Swing
        696,  // Malicious Moonsault
        699,  // Soul-Stealing 7-Star Strike
        701,  // Pulverizing Pancake
        706,  // Psychic Fangs
        707,  // Stomping Tantrum
        709,  // Accelerock
        710,  // Liquidation
        712,  // Spectral Thief
        713,  // Sunsteel Strike
        716,  // Zing Zap
        718,  // Multi-Attack
        721,  // Plasma Fists
        724,  // Searing Sunraze Smash
        726,  // Let's Snuggle Forever
        729,  // Zippy Zap
        731,  // Floaty Fall
        735,  // Sizzly Slide
        741,  // Veevee Volley
        742,  // Double Iron Bash
        746,  // Jaw Lock
        754,  // Bolt Beak
        755,  // Fishious Rend
        776,  // Body Press
        779,  // Snap Trap
        781,  // Behemoth Blade
        782,  // Behemoth Bash
        784,  // Breaking Swipe
        785,  // Branch Poke
        789,  // Spirit Break
        793,  // False Surrender
        798,  // Steel Roller
        803,  // Grassy Glide
        806,  // Skitter Smack
        808,  // Lash Out
        812,  // Flip Turn
        813,  // Triple Axel
        814,  // Dual Wingbeat
        817,  // Wicked Blow
        818,  // Surging Strikes
        823,  // Thunderous Kick
        827,  // Dire Claw
        828,  // Psyshield Bash
        830,  // Stone Axe
        834,  // Wave Crash
        838,  // Headlong Rush
        845,  // Ceaseless Edge
        853,  // Axe Kick
        857,  // Jet Punch
        859,  // Spin Out
        860,  // Population Bomb
        861,  // Ice Spinner
        862,  // Glaive Rush
        865,  // Triple Dive
        866,  // Mortal Spin
        869,  // Kowtow Cleave
        872,  // Aqua Step
        873,  // Raging Bull
        875,  // Psyblade
        878,  // Collision Course
        879,  // Electro Drift
        884,  // Pounce
        885,  // Trailblaze
        887,  // Hyper Drill
        889,  // Rage Fist
        891,  // Bitter Blade
        892,  // Double Shock
        894,  // Comeuppance
        910,  // Mighty Cleave
        912,  // Hard Press
        915,  // Temper Flare
        916,  // Supercell Slam
        918,  // Upper Hand
    ]

    /// Punching moves — Showdown's `punch` move flag, which Punching Glove reads.
    static let punching: Set<Int> = [
        4,  // Comet Punch
        5,  // Mega Punch
        7,  // Fire Punch
        8,  // Ice Punch
        9,  // Thunder Punch
        146,  // Dizzy Punch
        183,  // Mach Punch
        223,  // Dynamic Punch
        264,  // Focus Punch
        309,  // Meteor Mash
        325,  // Shadow Punch
        327,  // Sky Uppercut
        359,  // Hammer Arm
        409,  // Drain Punch
        418,  // Bullet Punch
        612,  // Power-Up Punch
        665,  // Ice Hammer
        721,  // Plasma Fists
        742,  // Double Iron Bash
        817,  // Wicked Blow
        818,  // Surging Strikes
        838,  // Headlong Rush
        857,  // Jet Punch
        889,  // Rage Fist
    ]

    /// Sound moves — Showdown's `sound` move flag, which Throat Spray reads. Kept apart from
    /// `bypassingSubstitute` (which every sound move also carries) because the two rules differ: a
    /// handful of non-sound moves bypass the doll too.
    static let sound: Set<Int> = [
        45,  // Growl
        46,  // Roar
        47,  // Sing
        48,  // Supersonic
        103,  // Screech
        173,  // Snore
        195,  // Perish Song
        215,  // Heal Bell
        253,  // Uproar
        304,  // Hyper Voice
        319,  // Metal Sound
        320,  // Grass Whistle
        336,  // Howl
        405,  // Bug Buzz
        448,  // Chatter
        496,  // Round
        497,  // Echoed Voice
        547,  // Relic Song
        555,  // Snarl
        568,  // Noble Roar
        574,  // Disarming Voice
        575,  // Parting Shot
        586,  // Boomburst
        590,  // Confide
        664,  // Sparkling Aria
        691,  // Clanging Scales
        728,  // Clangorous Soulblaze
        775,  // Clangorous Soul
        786,  // Overdrive
        826,  // Eerie Spell
        871,  // Torch Song
        914,  // Alluring Voice
        917,  // Psychic Noise
    ]

    /// Moves that reach the owner **through** a Substitute — every sound move, plus the few
    /// others Showdown marks with the `bypasssub` flag. The engine implements the doll once and
    /// asks here which moves ignore it, so a new sound move is not blocked in silence.
    static let bypassingSubstitute: Set<Int> = [
        18,  // Whirlwind
        45,  // Growl
        46,  // Roar
        47,  // Sing
        48,  // Supersonic
        50,  // Disable
        102,  // Mimic
        103,  // Screech
        114,  // Haze
        166,  // Sketch
        173,  // Snore
        174,  // Curse
        176,  // Conversion 2
        180,  // Spite
        193,  // Foresight
        194,  // Destiny Bond
        195,  // Perish Song
        213,  // Attract
        215,  // Heal Bell
        227,  // Encore
        244,  // Psych Up
        253,  // Uproar
        259,  // Torment
        269,  // Taunt
        270,  // Helping Hand
        272,  // Role Play
        285,  // Skill Swap
        286,  // Imprison
        288,  // Grudge
        289,  // Snatch
        304,  // Hyper Voice
        316,  // Odor Sleuth
        319,  // Metal Sound
        320,  // Grass Whistle
        357,  // Miracle Eye
        382,  // Me First
        384,  // Power Swap
        385,  // Guard Swap
        391,  // Heart Swap
        405,  // Bug Buzz
        432,  // Defog
        448,  // Chatter
        495,  // After You
        496,  // Round
        497,  // Echoed Voice
        513,  // Reflect Type
        516,  // Bestow
        547,  // Relic Song
        555,  // Snarl
        568,  // Noble Roar
        574,  // Disarming Voice
        575,  // Parting Shot
        586,  // Boomburst
        587,  // Fairy Lock
        589,  // Play Nice
        590,  // Confide
        593,  // Hyperspace Hole
        597,  // Aromatic Mist
        600,  // Powder
        602,  // Magnetic Flux
        607,  // Hold Hands
        621,  // Hyperspace Fury
        664,  // Sparkling Aria
        674,  // Gear Up
        683,  // Speed Swap
        689,  // Instruct
        691,  // Clanging Scales
        712,  // Spectral Thief
        728,  // Clangorous Soulblaze
        752,  // Teatime
        786,  // Overdrive
        791,  // Life Dew
        811,  // Coaching
        816,  // Jungle Healing
        826,  // Eerie Spell
        871,  // Torch Song
        913,  // Dragon Cheer
        914,  // Alluring Voice
        917,  // Psychic Noise
    ]

    /// How much max HP each Substitute-raising move charges, as the divisor Showdown writes in
    /// the move's own `onHit` callback: Substitute a quarter, Shed Tail half. The doll itself is
    /// always a quarter of max HP — only the price differs, so only the price is read out here.
    /// Moves Heal Block stops, as Showdown's `heal` move flag marks them — drain moves included
    /// (Showdown's own `healblock` condition disables every move carrying the flag).
    static let healing: Set<Int> = [
        71,  // Absorb
        72,  // Mega Drain
        105,  // Recover
        135,  // Soft-Boiled
        138,  // Dream Eater
        141,  // Leech Life
        156,  // Rest
        202,  // Giga Drain
        208,  // Milk Drink
        234,  // Morning Sun
        235,  // Synthesis
        236,  // Moonlight
        256,  // Swallow
        273,  // Wish
        303,  // Slack Off
        355,  // Roost
        361,  // Healing Wish
        409,  // Drain Punch
        456,  // Heal Order
        461,  // Lunar Dance
        505,  // Heal Pulse
        532,  // Horn Leech
        570,  // Parabolic Charge
        577,  // Draining Kiss
        613,  // Oblivion Wing
        659,  // Shore Up
        666,  // Floral Healing
        668,  // Strength Sap
        685,  // Purify
        733,  // Bouncy Bubble
        791,  // Life Dew
        816,  // Jungle Healing
        849,  // Lunar Blessing
        863,  // Revival Blessing
        891,  // Bitter Blade
        902,  // Matcha Gotcha
    ]

    static let substituteCostDivisor: [Int: Int] = [
        164: 4,  // Substitute
        880: 2,  // Shed Tail
    ]
}

extension MoveSpec {
    /// This spec with Showdown's corrections applied. Called once per spec in `MoveSpec.from`,
    /// so a cached spec carries the corrected values and the wire never sees the PokéAPI gaps.
    func applyingShowdownOverrides() -> MoveSpec {
        guard let override = ShowdownMoveData.overrides[id] else { return self }
        var corrected = self
        if override.alwaysHits { corrected.accuracy = nil }
        if let accuracy = override.accuracy { corrected.accuracy = accuracy }
        if let power = override.power { corrected.power = power }
        if let critRate = override.critRate { corrected.critRate = critRate }
        if let drain = override.drain { corrected.drain = drain }
        if let healing = override.healing { corrected.healing = healing }
        if let minHits = override.minHits { corrected.minHits = minHits }
        if let maxHits = override.maxHits { corrected.maxHits = maxHits }
        if let ailment = override.ailment { corrected.ailment = ailment }
        if let ailmentChance = override.ailmentChance { corrected.ailmentChance = ailmentChance }
        if let statChance = override.statChance { corrected.statChance = statChance }
        if let flinchChance = override.flinchChance { corrected.flinchChance = flinchChance }
        return corrected
    }
}
