// Generated by scripts/extract-showdown-moves.mjs — do not edit by hand.
//
// Move values PokéAPI gets wrong or never supplies, mirrored from Pokémon Showdown's
// data/moves.ts (MIT). PokéAPI's `move_meta` table stops at generation 7, so most gen-8+
// moves decode with no multi-hit, drain, ailment, flinch or crit-rate at all, and it writes
// `0` rather than null for a move that never misses.
//
// Only plain data lives here. Moves Showdown expresses as callbacks (variable power, volatile
// statuses, weather) need engine support instead — see `VariableDamage` and the script's report.

/// One move's corrections. Every field is optional: an absent field keeps the PokéAPI value.
struct ShowdownMoveOverride: Sendable {
    /// The move never misses — the engine spells that `MoveSpec.accuracy == nil`.
    var alwaysHits = false
    var accuracy: Int?
    var power: Int?
    var critRate: Int?
    var drain: Int?
    var healing: Int?
    var minHits: Int?
    var maxHits: Int?
    var ailment: String?
    var ailmentChance: Int?
    var statChance: Int?
    var flinchChance: Int?
}

enum ShowdownMoveData {
    /// Keyed by PokéAPI move id (Showdown's `num`).
    static let overrides: [Int: ShowdownMoveOverride] = [
        290: .init(ailment: "paralysis"),  // Secret Power
        622: .init(power: 1),  // Breakneck Blitz
        624: .init(power: 1),  // All-Out Pummeling
        626: .init(power: 1),  // Supersonic Skystrike
        628: .init(power: 1),  // Acid Downpour
        630: .init(power: 1),  // Tectonic Rage
        632: .init(power: 1),  // Continental Crush
        634: .init(power: 1),  // Savage Spin-Out
        636: .init(power: 1),  // Never-Ending Nightmare
        638: .init(power: 1),  // Corkscrew Crash
        640: .init(power: 1),  // Inferno Overdrive
        642: .init(power: 1),  // Hydro Vortex
        644: .init(power: 1),  // Bloom Doom
        646: .init(power: 1),  // Gigavolt Havoc
        648: .init(power: 1),  // Shattered Psyche
        650: .init(power: 1),  // Subzero Slammer
        652: .init(power: 1),  // Devastating Drake
        654: .init(power: 1),  // Black Hole Eclipse
        656: .init(power: 1),  // Twinkle Tackle
        733: .init(drain: 50),  // Bouncy Bubble
        831: .init(statChance: 30),  // Springtide Storm
        834: .init(drain: -33),  // Wave Crash
        836: .init(flinchChance: 30),  // Mountain Gale
        839: .init(ailment: "poison", ailmentChance: 50),  // Barb Barrage
        840: .init(critRate: 1),  // Esper Wing
        841: .init(statChance: 100),  // Bitter Malice
        843: .init(critRate: 1, statChance: 50),  // Triple Arrows
        844: .init(ailment: "burn", ailmentChance: 30),  // Infernal Parade
        846: .init(statChance: 30),  // Bleakwind Storm
        847: .init(ailment: "paralysis", ailmentChance: 20),  // Wildbolt Storm
        848: .init(ailment: "burn", ailmentChance: 20),  // Sandsear Storm
        853: .init(ailment: "confusion", ailmentChance: 30),  // Axe Kick
        855: .init(statChance: 100),  // Lumina Crash
        860: .init(minHits: 10, maxHits: 10),  // Population Bomb
        865: .init(minHits: 3, maxHits: 3),  // Triple Dive
        866: .init(ailment: "poison", ailmentChance: 100),  // Mortal Spin
        877: .init(power: 0),  // Ruination
        884: .init(statChance: 100),  // Pounce
        886: .init(statChance: 100),  // Chilling Water
        888: .init(minHits: 2, maxHits: 2),  // Twin Beam
        891: .init(drain: 50),  // Bitter Blade
        894: .init(power: 0),  // Comeuppance
        895: .init(critRate: 1),  // Aqua Cutter
        896: .init(ailment: "burn", ailmentChance: 30),  // Blazing Torque
        897: .init(ailment: "sleep", ailmentChance: 10),  // Wicked Torque
        898: .init(ailment: "poison", ailmentChance: 30),  // Noxious Torque
        899: .init(ailment: "paralysis", ailmentChance: 30),  // Combat Torque
        900: .init(ailment: "confusion", ailmentChance: 30),  // Magical Torque
        902: .init(drain: 50, ailment: "burn", ailmentChance: 20),  // Matcha Gotcha
        904: .init(critRate: 1),  // Ivy Cudgel
        908: .init(alwaysHits: true),  // Burning Bulwark
        911: .init(alwaysHits: true, minHits: 2, maxHits: 2),  // Tachyon Cutter
        913: .init(alwaysHits: true),  // Dragon Cheer
        918: .init(flinchChance: 100),  // Upper Hand
        919: .init(ailment: "poison", ailmentChance: 50),  // Malignant Chain
    ]
}

extension MoveSpec {
    /// This spec with Showdown's corrections applied. Called once per spec in `MoveSpec.from`,
    /// so a cached spec carries the corrected values and the wire never sees the PokéAPI gaps.
    func applyingShowdownOverrides() -> MoveSpec {
        guard let override = ShowdownMoveData.overrides[id] else { return self }
        var corrected = self
        if override.alwaysHits { corrected.accuracy = nil }
        if let accuracy = override.accuracy { corrected.accuracy = accuracy }
        if let power = override.power { corrected.power = power }
        if let critRate = override.critRate { corrected.critRate = critRate }
        if let drain = override.drain { corrected.drain = drain }
        if let healing = override.healing { corrected.healing = healing }
        if let minHits = override.minHits { corrected.minHits = minHits }
        if let maxHits = override.maxHits { corrected.maxHits = maxHits }
        if let ailment = override.ailment { corrected.ailment = ailment }
        if let ailmentChance = override.ailmentChance { corrected.ailmentChance = ailmentChance }
        if let statChance = override.statChance { corrected.statChance = statChance }
        if let flinchChance = override.flinchChance { corrected.flinchChance = flinchChance }
        return corrected
    }
}
